2단계 - 로또(자동)
xrabcde/kotlin-lotto pull request #2
Opened 2022-07-07 14:06 UTC by xrabcde

2022-07-08 09:43 UTC, Hyeon9mak requested changes
코틀린 pirmary 생성자와 init 키워드를 조금 잘못 사용하신 것 같아요!
그래도 최대한 살살 리뷰 남겨드렸으니 포기하지 말고 다시 해봅시다!

2022-07-08 09:43 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/Lotto.kt
> +    }
InputView에서 문자열로 바뀐 채로 들어와도 괜찮을거 같아요. 
Lotto 라는 도메인에서는 '숫자 값'이 중요한거지, '문자열 -> 숫자'가 중요한게 아니니까요!

2022-07-08 09:43 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/Lotto.kt
> +    }
👍

2022-07-08 09:43 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/Lottos.kt
> +}
수동 로또가 벌써.. 😇

2022-07-08 14:20 UTC, xrabcde commented on src/main/kotlin/lotto/domain/Lotto.kt
> +    }
으으으으으ㅡㅁ 그러면 Integer가 아닌 입력에 대한 예외처리를 View에서 하게 되는데
View에서 예외를 던지는 것이 테스트하기 어렵기도 하고  View가 서비스로직을 알고 있는 것 같다고 생각했는데
어떻게 생각하시나요????!??

2022-07-08 14:22 UTC, xrabcde commented on src/main/kotlin/lotto/domain/Lotto.kt
> +    }
자동차경주에서 배웠던 거 응용 좀 해봤습니다 ^0^

2022-07-08 14:22 UTC, xrabcde commented on src/main/kotlin/lotto/domain/Lottos.kt
> +}
🫣

2022-07-08 14:32 UTC, xrabcde commented on src/test/kotlin/lotto/domain/LottoTest.kt
> +    "생성자에 아무것도 넘겨주지 않으면 랜덤(자동)로또를 생성한다." {
오 KoTest에서도 companion object를 쓸 수가 있군여

2022-07-08 15:20 UTC, xrabcde commented on src/main/kotlin/lotto/domain/Money.kt
> +    }
그쵸 .... 이게 애매하긴 한데... 흠 🤔

2022-07-10 00:13 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/Money.kt
> +    }
Money 객체가 나중에 재활용 될 가능성이 있는 객체라고 생각한다면 빼는게 이상적일거 같아요 ㅎㅎ

2022-07-10 00:17 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/Lotto.kt
> +    }
저는 View의 역할을 Spring의 Controller + RequestDto 정도로 생각하는데요,
저희가 Long, LocalDateTime 등의 정보를 받을 때 별도의 변환을 해주지 않아도 스프링이 변환을 해주잖아요?
거기까지가 모두 View의 역할이라고 생각해요.

`Lotto` 객체가 해야하는 일의 1순위는 로또 역할을 수행할 객체로 변신하는 것, 2순위가 주어진 숫자들이 유효한 로또 숫자인지 확인하는거라 생각해요. 문자열로 들어온 값을 숫자로 변환하는 건 다른 녀석이 해줘도 괜찮을거 같다는 생각이에요.

2022-07-10 00:25 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/Lotto.kt
> +    }
결국 "View의 역할이 어디까지인가"를 고민할 때 가장 명확한 판단 기준은 "View를 교체할 때 어떤 일이 일어날까"를 상상해보는거에요.

- "지금은 키보드로 입력 받지만, 터치방식으로 바뀐다면?"
- "스프링 Request 객체가 다 변환해서 받아준다면?"
- (계산기를 만들 때) "무조건 문자열이 아닌 숫자만 들어온다면?"

저도 많이 헷갈렸던 지라 무슨 마음일지 이해가 가니까, 혹시나 여전히 이해하기 어렵다면 얼마든지 추가 코멘트 남겨주세요.

2022-07-10 14:25 UTC, xrabcde commented on src/main/kotlin/lotto/domain/Lotto.kt
> +    }
> `Lotto` 객체가 해야하는 일의 최 우선순위는 로또 역할을 수행할 객체로 변신하는거라 생각해요. 문자열로 들어온 값을 숫자로 변환하는 건 다른 녀석이 해줘도 괜찮을거 같다는 생각이에요.

넹 저도 이 의견에는 동의하는데 
문자열을 숫자로 변환하는 일은 Lotto의 역할도 View의 역할도 아닌 것 같은 애매한 느낌이네욥... ㅋㅎㅋㅎ....
그나마 View 안에서 입력을 받는 로직과 입력값을 검증하는 로직을 분리해서 
검증하는 쪽만 테스트를 짜는 방식이 최선인가 싶기도...!??!

2022-07-19 01:03 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/WinningResult.kt
> +    }
Lotto 에서 Set을 뽑아서 minus().size를 이용하기 전에 객체에 메세지를 보내면 가독성이 훨씬 올라갈거 같아요.
그런 구조를 갖게 되면 WinningResult가 LOTTO_DIGIT이라는 상수를 알 필요도 없지 않을까요?

2022-07-19 01:04 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/WinningResult.kt
> +    }
!!을 사용해서 조회에 실패하면 NPE가 발생하는데요, 다른 조회 방법이 있을지 찾아보면 좋을거 같아요~

2022-07-19 04:10 UTC, xrabcde commented on src/main/kotlin/lotto/domain/Lotto.kt
> +    }
> 주생성자 파라미터 이름을 _numbers로 한 이유가 있을까요?

이거는 코틀린인액션에서 프로퍼티와 생성자 파라미터를 이런식으로 구분하길래 뭔가 코틀린 컨벤션인줄 알았는데 질문하시는 거 보니 그런건 아닌가보네요 ㅋㅋㅋ

2022-07-19 04:12 UTC, xrabcde commented on src/main/kotlin/lotto/domain/Lottos.kt
> +
읭... Lotto의 numbers와 헷갈렸네요 ㅋㅋㅋ 제삼다...

2022-07-23 10:03 UTC, xrabcde commented on src/main/kotlin/lotto/domain/WinningResult.kt
> +    }
그러네.... 기가 막히네요.....

2022-07-23 14:11 UTC, xrabcde commented on src/main/kotlin/lotto/domain/WinningResult.kt
> +    }
불변 컬렉션을 사용하려다 보니 계속 계산결과를 덮어씌우는 과정에서
```
map = map.plus(rank, 1)
```
처럼 코드를 작성하게 되었는데...
**plus**라는 친구를 이렇게 남발해도 되나.. 싶어서요.... 괜찮은가요??? ([커밋](https://github.com/xrabcde/kotlin-lotto/pull/2/commits/3663e404c98eff9aeb799d078b487d700ca20b00))

2022-07-23 14:22 UTC, xrabcde commented on src/main/kotlin/lotto/domain/Lotto.kt
> +    }
리뷰어님 덕분에 코틀린 생성자는 확실히 배웠네요 ^0^... 
감명받아 [글로도 정리해보았어요](https://xrabcde.github.io/kotlin-constructor/).. 그럼 이만.... 🙇🏻‍♀️

2022-07-25 23:50 UTC, Hyeon9mak approved these changes
이번 PR 너무 많이 고생하셨고, 코틀린 생성자 개념에 대해 꽉 잡는 시간이었던거 같아서 뿌듯하네요 ㅎㅎ
다음 PR에선 불변 컬렉션에 대해서도 꽉 잡고 갔으면 해요!

> LottoMachine은 Controller로 패키지에 속해있는거 같은데요, 비즈니스 로직에 사용되는 상수를 가지고 있는걸 보아 컨트롤러 이상으로 사용되고 있는거 같아요. 컨트롤러와 도메인의 차이가 무엇일까요?

> 파라미터에 ?를 허용하고, 검증 메서드에는 !!를 사용한 이유가 있을까요?

질문에 대한 대답도 적어주시면 좋을거 같아요!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

2022-07-25 23:50 UTC, Hyeon9mak commented on src/main/kotlin/lotto/view/View.kt
> +    }
```kotlin
return readln().toIntOrNull()
    ?: throw IllegalArgumentException("높이는 숫자만 입력 가능합니다.")
```

`toIntOrNull()`을 통해 "변환을 실패하면 Null로 처리" 시키고,
Null을 잡아서 Exception 처리하는 것도 가능합니다 👍

2022-07-25 23:50 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/Lotto.kt
> +    }
```kotlin
numbers.intersect(other.numbers).size
```

[intersect(교집합)](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/intersect.html)을 이용할 수도 있을거 같네요.

2022-07-25 23:50 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/Lotto.kt
> +    }
속이 다 후련 ^_^

2022-07-25 23:50 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/Lottos.kt
> +    }
List는 불변이 되었지만 List를 프로퍼티로 삼은 values는 가변이 되었네요. 또 다른 해결 방법이 없을까요? 🤔 
(불변을 활용하는 방법이 익숙치 않아 보여서, 다음 PR에선 꽉 잡고 갔으면 해요.)

2022-07-25 23:50 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/Lottos.kt
> +        }
`Lottos` 라는 이름은 일급 컬렉션 같은데, 그 이상의 역할을 수행하는거 같아요.
로또를 구매하는 것은 LottoMachine이라는 이름에 조금 더 적합한 행동으로 보여요.

그렇다고 Controller 패키지에 속한 LottoMachine 클래스가 도메인 로직을 수행하는 건 유지보수가 어려울거 같고... 🤔 
어떻게 해결하면 좋을까요?

2022-07-25 23:50 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/Money.kt
> +}
Money 간 동등성 비교가 안될거 같네요 😢

2022-07-25 23:50 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/Rank.kt
> +    }
승리계산...?!

2022-07-25 23:50 UTC, Hyeon9mak commented on src/test/kotlin/lotto/domain/LottosTest.kt
> +    }
로또 구매 가격이 얼마인지도 적어주면 더 많은 도움이 되겠죠!?

2022-07-25 23:50 UTC, Hyeon9mak commented on src/test/kotlin/lotto/domain/MoneyTest.kt
> +    }
항상 테스트 가독성은 기가 막히네요...

2022-07-25 23:50 UTC, Hyeon9mak commented on src/test/kotlin/lotto/domain/MoneyTest.kt
> +    }
요런 메세지 / 금액 등 상수값들은 테스트 메서드 내부에 raw 하게 사용하는게 더 좋다고 생각해요!
'내가 짠 로직이 잘 돌아가?' 보다 '내가 짠 로직이 올바른 결과를 내뱉어?'가 우리의 주 관심사니까요.

2022-07-25 23:50 UTC, Hyeon9mak commented on src/test/kotlin/lotto/domain/RankTest.kt
> +    }
hot girl 🔥

2022-07-26 01:45 UTC, xrabcde commented on src/main/kotlin/lotto/domain/Rank.kt
> +    }
당첨금.... 계산... 을 말하고 싶었담니다.....
<img width="684" alt="image" src="https://user-images.githubusercontent.com/56033755/180904590-73c394a6-7f2c-4e5c-aaf3-fded51d82f26.png">

2022-07-26 01:46 UTC, xrabcde commented on src/main/kotlin/lotto/domain/Lotto.kt
> +    }
ㅋㅋㅋㅋㅋㅋㅋㅋ

2022-07-26 01:49 UTC, xrabcde commented on src/main/kotlin/lotto/domain/Lottos.kt
> +    }
다음 글감은 불변인가.....

2022-07-31 09:03 UTC, merged

2022-08-17 12:09 UTC, xrabcde commented on src/main/kotlin/lotto/domain/Money.kt
> +}
근데 Money가 동등성 비교가 되어야하는 이유가 뭔가욥...? 
만원짜리 두 장은 서로 다른 만원인데...

2022-08-17 12:16 UTC, xrabcde commented on src/test/kotlin/lotto/domain/MoneyTest.kt
> +    }
흠... 그것도 아주 일리가 있는 말이네요....
취향의 차이인듭ㅅ...ㅎ....ㅎㅎ

2022-08-18 01:58 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/Money.kt
> +}
로또를 구매할 때 지폐 일련번호를 비교하는 로직을 넣는다면 인정하겠습니다 ㅋ_ㅋ