3단계 - 로또(수동)
xrabcde/kotlin-lotto pull request #3
Opened 2022-08-17 11:59 UTC by xrabcde

2022-08-18 02:01 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/LottoNumber.kt
> +    }
oh!!!!!!!!!!!!!!!!!! 💯

2022-09-13 13:16 UTC, Hyeon9mak requested changes
거의 다 왔다!

2022-09-13 13:16 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/LottoNumber.kt
> +        }
파라미터 명칭을 포함해서 볼 땐 개수만큼 숫자를 뽑아낸다를 유추할 수 있는데요,
메서드 명칭만 보아서는 그걸 유추하기 어려울 것 같아요. 또한 '랜덤한' 값을 뽑는다는게 함께 표현되면 어떨까요?

2022-09-13 13:16 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/LottoNumber.kt
> +    }
맞아유 이건 LottoNumber의 책임이죠

2022-09-13 13:16 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/Rank.kt
>      NONE(0, Money(0));
오... 파라미터 기본값으로 false를 두고 true 만 사용해서 2등을 강조... 💯 👍

2022-09-13 13:16 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/WinningLottoSet.kt
> +        require(!winningLotto.numbers.contains(bonusBall)) { "당첨 번호와 보너스볼은 중복될 수 없습니다." }
Lotto 객체에 메세지를 전달할 수 있겠네요. 그럼 getter도 사라지고, `require` 사이에 들어간 `!` 도 가려지면서 가독성이 더욱 올라가겠죠?

2022-09-13 13:16 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/WinningLottoSet.kt
> +    }
역시나 메세지를 보낼 수 있을거 같아요

2022-09-13 13:16 UTC, Hyeon9mak commented on src/test/kotlin/lotto/domain/RankTest.kt
>      }
나누는 것도 테스트를 쉽게 짜는 좋은 방법이죠 👍

2022-09-13 13:16 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/LottoMachine.kt
> +        return WinningResult(result)
리뷰가 늦어서 시간이 많이 흐른 지금!(🙏) 
한 눈에 로직을 이해할 수 있고, 유지보수가 용이한지 물어보고 싶어요. `newValue`가 어떤 의미로 사용된건지 바로 떠오르나요?
저는 사실 한참 봤어요... 🥲 메서드로 동작을 분리하고 이름을 부여하는 이유에 대해 고민해보면서 조금 더 다듬어보면 좋을거 같아요.
(calculateRank는 의미도 잘 부여했고 내부도 깔끔하고 너무 훌륭 👍)

2022-09-14 10:42 UTC, xrabcde commented on src/main/kotlin/lotto/domain/Lotto.kt
> +            throw IllegalArgumentException("로또번호를 중복되지 않은 ${LOTTO_DIGIT}자리로 입력해주세요.")
자릿수... 뭐가 좋을까요... 제 영어실력으로는 DIGIT이 최선인데.. 

<img width="1184" alt="image" src="https://user-images.githubusercontent.com/56033755/190133320-5112433d-a5c9-492e-a20f-d1abf6766f55.png">

2022-09-14 10:42 UTC, xrabcde commented on src/main/kotlin/lotto/domain/LottoNumber.kt
> +    }
이~

2022-09-14 10:43 UTC, xrabcde commented on src/main/kotlin/lotto/domain/Rank.kt
>      NONE(0, Money(0));
제법 코틀린 고수 같았죠 ?

2022-09-14 10:43 UTC, xrabcde commented on src/test/kotlin/lotto/domain/RankTest.kt
>      }
이이~

2022-09-15 08:56 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/Lotto.kt
> +            throw IllegalArgumentException("로또번호를 중복되지 않은 ${LOTTO_DIGIT}자리로 입력해주세요.")
digit은 자리 수의 개념을 의미하지(10 = 2자리 수, 100 = 3자리 수), 로또 번호 개수를 의미하는 건 아닌거 같아요 😢

2022-09-17 06:07 UTC, xrabcde commented on src/main/kotlin/lotto/domain/Lotto.kt
> +            throw IllegalArgumentException("로또번호를 중복되지 않은 ${LOTTO_DIGIT}자리로 입력해주세요.")
오 예리한데.. ~

2022-09-17 08:48 UTC, xrabcde commented on src/main/kotlin/lotto/domain/LottoMachine.kt
> +        return WinningResult(result)
당첨통계 계산로직을 더 깔끔하게 정리하기 위해 

1) Rank 에 index 필드를 추가하고
2) Rank가 하던 수익률 계산을 WinningResult가 하도록 

수정했습니당 '-'

2022-09-18 07:14 UTC, Hyeon9mak approved these changes
cool girl

2022-09-18 07:14 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/LottoMachine.kt
>          }
한 눈에 이해가 되네요 👍

2022-09-18 07:14 UTC, Hyeon9mak commented
가라!

2022-09-18 07:15 UTC, merged