4단계 : 로또(수동)
xrabcde/kotlin-lotto pull request #4
Opened 2022-09-27 11:17 UTC by xrabcde

2022-09-28 12:11 UTC, Hyeon9mak commented
조금 더 찬찬히 보겠슈

2022-09-29 01:24 UTC, Hyeon9mak requested changes
코드 전반적으로 생략된 내용이 많았어요 😢 
도메인에 대한 이해가 굉장히 높은 개발자가 짠 코드네요!
로또 도메인을 처음 접하는 신입 개발자를 위해 조금만 더 친절하게 해주는건 어떨까요?

2022-09-29 01:24 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/LottoCount.kt
> +) {
수동과 자동에 대한 개수는 정수로 사용되는데, 그 둘에 대한 모음집은 `LottoCount` 라는 명칭을 사용하고 있어서 조금 헷갈리는 것 같아요.

2022-09-29 01:24 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/LottoCount.kt
> +    }
각각을 포장한다면 요 검증로직 또한 분리될 수 있을 것 같아요.

2022-09-29 01:24 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/LottoCount.kt
> +        private val LOTTO_PRICE = Money(1000)
'로또 1장당 가격은 얼마일까?' 라는 의문이 생겼을 때 가장 먼저 접근할 수 있는 객체는 무엇일까요? 저는 `LottoPrice` 혹은 `LottoTicket`, `Lotto` 등의 네이밍을 가진 객체를 찾을 것 같아요.

`LottoCount` 객체에 많은 역할을 부여하려다보니 직관성이 떨어져서 아쉬운 것 같아요...

2022-09-29 01:24 UTC, Hyeon9mak commented on src/main/kotlin/lotto/controller/LottoController.kt
> +        val lottoCount = LottoCount.from(money, manualCount)
'수동개수'와 '로또개수'는 굉장히 많은 의미를 내포하고 있는 것 같아요.

2022-09-29 01:24 UTC, Hyeon9mak commented on src/main/kotlin/lotto/controller/LottoController.kt
> +        }
> 로또 개수가 수동 개수를 갖고 있으면 수동 번호를 입력 받는다.

요구사항과 주어진 예시에 맞춰 딱딱하게 대화하는거 같아요 😄 
조금 더 자연스럽게 대화해보면 어떨까요?

2022-09-29 01:24 UTC, Hyeon9mak commented on src/main/kotlin/lotto/controller/LottoController.kt
> +        view.printLottos(lottoCount, lottoMachine.lottos)
내부에서 어떤 일이 일어나고 있을까요?

2022-09-29 01:24 UTC, Hyeon9mak commented on src/main/kotlin/lotto/view/View.kt
> +        return manualLottos
계속해서 가변리스트가 사용된 이유가 있을까요?

2022-10-09 11:02 UTC, xrabcde commented on src/main/kotlin/lotto/domain/Lottos.kt
>          }
😧....!

2022-10-09 11:04 UTC, xrabcde commented on src/main/kotlin/lotto/view/View.kt
> +        return manualLottos
외부에서 반복을 돌리도록 수정하면 되겠군여

2022-10-09 11:06 UTC, xrabcde commented on src/main/kotlin/lotto/domain/LottoCount.kt
> +        private val LOTTO_PRICE = Money(1000)
그게 좀 찜찜하긴 했는데....

2022-10-09 11:06 UTC, xrabcde commented on src/main/kotlin/lotto/domain/LottoCount.kt
> +    }
좀 더 구체적인 이름을 사용하겟슴다 ~~

2022-10-09 11:08 UTC, xrabcde commented on src/main/kotlin/lotto/controller/LottoController.kt
> +        view.printLottos(lottoCount, lottoMachine.lottos)
어떤 내부를 질문하신 걸까욤... start()의 내부인가요?!?!

2022-10-10 08:30 UTC, Hyeon9mak commented on src/main/kotlin/lotto/controller/LottoController.kt
> +        view.printLottos(lottoCount, lottoMachine.lottos)
yes

2022-10-10 08:45 UTC, Hyeon9mak requested changes
함께 고민해보면 좋을 것 같아서 코멘트 조금 더 남겼어요~

2022-10-10 08:45 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/Money.kt
> +data class Money(val price: Long) {
👍

2022-10-10 08:45 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/lottoTicket/Lottos.kt
> +}
별다른 비즈니스 로직이 없는 것 같은데 일급 컬렉션으로 감싼 이유가 있을까요? 감쌌을 때 장점과 단점은 무엇일까요?

2022-11-20 11:45 UTC, xrabcde commented on src/main/kotlin/lotto/domain/lottoTicket/Lottos.kt
> +}
원래는 Lottos를 생성하면서 수동로또, 자동로또를 생성하고 등수와 결과를 계산하기 위해 분리했던 것 같은데
리팩터링 하다보니 이제 그 역할을 LottoMachine에서 하게 되어 역할이 희미해졌군요 !

2022-11-20 12:21 UTC, xrabcde commented on src/main/kotlin/lotto/controller/LottoController.kt
> +        view.printLottos(manualCount, autoCount, lottoMachine.lottos)
음... 이렇게 하니까 controller에서 계산로직이 빠지게되어 좋지만
수동로또개수는 ManualLottoCount라는 객체로 관리하고
자동로또개수는 LottoMachine안의 autoLottoCount라는 필드로 관리하는 구조가 
쵸큼 구린거 같기도.. 하네욤...

2022-11-21 01:31 UTC, Hyeon9mak approved these changes
이번 미션에서 충분히 많은 고민을 거치고 리팩터링도 많이 진행되었네요~
모두 반영하기 힘들었을텐데 긴 시간 고생 많았습니다! 블랙잭 미션도 화이팅 해봅시다!

2022-11-21 01:31 UTC, Hyeon9mak commented on README.md
> +- [x] 입력한 수동로또 개수와 발급된 자동로또 개수 출력
👍

2022-11-21 01:31 UTC, Hyeon9mak commented on src/main/kotlin/lotto/controller/LottoController.kt
> +        val totalCount = money.divideBy(LottoPrice().price)
딱 한번만 사용되는 값 같은데 인스턴스를 생성할 필요가 없어보여요 😨

2022-11-21 01:31 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/lottoTicket/ManualLottoCount.kt
> +            }
require 로 대체 가능하겠네요 😄

2022-11-21 05:20 UTC, xrabcde commented on src/main/kotlin/lotto/controller/LottoController.kt
> +        val totalCount = money.divideBy(LottoPrice().price)
흠.... 그렇네요.. 😢

2023-01-02 02:43 UTC, merged